version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: devops/nginx/Dockerfile
    container_name: nginx
    volumes:
      - ./:/var/www/E-obuwie/
    ports:
      - 8000:80
    networks:
      - symfony
  php:
    container_name: php
    build:
      context: .
      dockerfile: devops/php/Dockerfile
    volumes:
      - ./:/var/www/E-obuwie/
    networks:
      - symfony

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e-obuwie
      MYSQL_USER: symfony
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - symfony


networks:
  symfony:
